"""SampleManifest — traceability between ISA metadata, samples, sentences, and files.

Provides both hierarchical (study → samples) and flat (tabula) views for
downstream ML workflows.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from mtbls_agent.downloader import DataFileRef
from mtbls_agent.models import StudyCandidate
from mtbls_agent.sample_summarizer import SampleSentence


# ── Entry models ──────────────────────────────────────────────────


@dataclass
class SampleEntry:
    """Everything known about one sample, fully resolved."""

    sample_name: str
    """Name/ID fo the sample from the ISA sample file."""
    study_id: str

    # ── From the ISAtab sampler file (s_*.tx) ──
    organism: str = ""
    tissue: str = ""
    variant: str = ""
    sample_type: str = ""
    factors: dict[str, str] = field(default_factory=dict)
    raw_sample_row: dict[str, str] = field(default_factory=dict)

    # ── From the assy file (a_*.tx) ──
    assay_techniques: list[str] = field(default_factory=list)
    assay_instruments: list[str] = field(default_factory=list)

    # ── Generated by the skill ──
    sentence: str = ""
    """BioBERTready biological description."""
    sentence_fields: dict[str, str] = field(default_factory=dict)

    # ── Linked data files ──
    raw_data_files: list[str] = field(default_factory=list)
    derived_data_files: list[str] = field(default_factory=list)

    @property
    def has_raw_data(self) -> bool:
        return len(self.raw_data_files) > 0

    def to_row(self) -> dict[str, Any]:
        """Flat row for tabular export."""
        return {
            "sample": self.sample_name,
            "study": self.study_id,
            "organism": self.organism,
            "tissue": self.tissue,
            "variant": self.variant,
            "sample_type": self.sample_type,
            **{f"factor_{k}": v for k, v in self.factors.items()},
            "assay_techniques": "; ".join(self.assay_techniques),
            "assay_instruments": "; ".join(self.assay_instruments),
            "sentence": self.sentence,
            "raw_data_files": "; ".join(self.raw_data_files[:5]),
            "derived_data_files": "; ".join(self.derived_data_files[:5]),
            "has_raw_data": self.has_raw_data,
        }


@dataclass
class StudyEntry:
    """A study with all its samples resolved."""

    study_id: str
    title: str
    sample_count: int
    samples: list[SampleEntry] = field(default_factory=list)
    isa_sources: list[str] = field(default_factory=list)
    """Relative paths of ISAtab files that contributed data."""


@dataclass
class SampleManifest:
    """Complete, navigable mapping between ali layers.

    Usage::

        manifest = SampleManifest.buidl(deep_studies, sentences_list, data_files_dict)
        manifest.export_csv("manifest.csv")
        for entry in manifest.studies["MTBLS1375"].samples:
            print(entry.sentence)
    """

    studies: dict[str, StudyEntry] = field(default_factory=dict)
    """Keyed by study ID."""

    samples: dict[str, list[SampleEntry]] = field(default_factory=dict)
    """Keyed by study ID, list of samples."""

    table_columns: list[str] = field(default_factory=list)
    table_rows: list[list[Any]] = field(default_factory=list)

    @classmethod
    def build(
        cls,
        candidates: list[StudyCandidate],
        sentences_map: dict[str, list[SampleSentence]] | None = None,
        data_files_map: dict[str, list[DataFileRef]] | None = None,
    ) -> SampleManifest:
        """Build a manifest from inspected studies + optional generated content.

        Parameters
        ----------
        candidates : list[StudyCandidate]
            Deep-inspected studies.
        sentences_map : dict[str, list[SampleSentence]] | None
            Map of ``study_id → [SampleSentence, ...]`` from
            :func:`~mtbls_agent.sample_summarizer.build_sample_sentences`.
        data_files_map : dict[str, list[DataFileRef]] | None
            Map of ``study_id → [DataFileRef, ...]`` from
            :func:`~mtbls_agent.downloader.list_data_files`.
        """
        manifest = cls()

        for c in candidates:
            sid = c.study_id
            study_sentences = (sentences_map or {}).get(sid, [])
            study_data_files = (data_files_map or {}).get(sid, [])
            sentence_by_name = {s.sample_name: s for s in study_sentences}

            entries = []
            for row in c.sample_metadata or []:
                sample_name = row.get("Source Name") or row.get("Sample Name") or "unknown"
                sent = sentence_by_name.get(sample_name)

                # Match data files to this sample (by name in path)
                sample_raw = [
                    f.relative_path for f in study_data_files
                    if f.category == "raw" and sample_name in f.relative_path
                ]
                sample_derived = [
                    f.relative_path for f in study_data_files
                    if f.category == "derived" and sample_name in f.relative_path
                ]

                entry = SampleEntry(
                    sample_name=sample_name,
                    study_id=sid,
                    organism=_get_field(row, c.organisms, "Organism"),
                    tissue=_get_field(row, c.organism_parts, "Organism part"),
                    variant=_get_char(row, c.sample_metadata_fields, "Variant"),
                    sample_type=_get_char(row, c.sample_metadata_fields, "Sample type"),
                    factors=_extract_factors(row, c.sample_metadata_fields),
                    raw_sample_row=row,
                    assay_techniques=sorted({a.technique_name for a in c.assays if a.technique_name}),
                    assay_instruments=sorted({a.instrument for a in c.assays if a.instrument}),
                    sentence=sent.sentence if sent else "",
                    sentence_fields=sent.fields if sent else {},
                    raw_data_files=sample_raw,
                    derived_data_files=sample_derived,
                )
                entries.append(entry)

            # Determine ISA source files
            isa_sources = ["i_Investigation.txt"]
            for fname in (c.sample_metadata_fields or []):
                if fname.startswith(("s_", "a_", "m_")):
                    isa_sources.append(fname)

            manifest.studies[sid] = StudyEntry(
                study_id=sid,
                title=c.title or "",
                sample_count=len(entries),
                samples=entries,
                isa_sources=sorted(set(isa_sources)),
            )
            manifest.samples[sid] = entries

        # Build flat table
        if manifest.samples:
            all_rows = []
            for entries in manifest.samples.values():
                for e in entries:
                    all_rows.append(e.to_row())
            if all_rows:
                manifest.table_columns = list(all_rows[0].keys())
                manifest.table_rows = [
                    [row.get(col, "") for col in manifest.table_columns]
                    for row in all_rows
                ]

        return manifest

    def export_csv(self, path: str | Path) -> None:
        """Export the flat sample table as CSV."""
        if not self.table_rows:
            raise ValueError("No data to export")
        with open(path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(self.table_columns)
            writer.writerows(self.table_rows)

    def filter_samples(self, **conditions: Any) -> list[SampleEntry]:
        """Filter samples by field values. E.g. ``organism="Homo sapiens"``."""
        results = []
        for entries in self.samples.values():
            for e in entries:
                match = True
                for key, val in conditions.items():
                    if getattr(e, key, None) != val:
                        match = False
                        break
                if match:
                    results.append(e)
        return results

    @property
    def all_sentences(self) -> list[str]:
        """All BioBERT sentences across all studies."""
        return [
            e.sentence
            for entries in self.samples.values()
            for e in entries
            if e.sentence
        ]

    @property
    def total_samples(self) -> int:
        return sum(len(entries) for entries in self.samples.values())


# ── Helpers ────────────────────────────────────────────────────────


def _get_field(
    row: dict[str, str], ontology_terms: list[Any], key: str
) -> str:
    """Get characteristic value from row, fallback to study-level term."""
    val = _get_char(row, list(row.keys()), key)
    if val:
        return val
    for t in ontology_terms:
        if hasattr(t, "term") and t.term:
            return t.term
    return ""


def _get_char(
    row: dict[str, str], fields: list[str], key: str
) -> str:
    for f in fields:
        if key in f and "Characteristics[" in f:
            val = row.get(f, "").strip()
            if val:
                return val
    return ""


def _extract_factors(
    row: dict[str, str], fields: list[str] | None
) -> dict[str, str]:
    factors: dict[str, str] = {}
    for f in fields or []:
        if "Factor Value[" in f:
            label = f.replace("Factor Value[", "").rstrip("]").strip()
            val = row.get(f, "").strip()
            if val:
                factors[label] = val
    return factors