"""Per-sample biological descriptions for BioBERT embedding.

Every sample gets a **concise biological sentence** generated by an LLM
(guided by a prompt template) that excludes all non-biological information:
no sample names, study IDs, software names, instruments, or techniques.

Usage::

    # Agent provides an LLM-based summarizer using the prompt template
    def my_summarizer(prompt: str) -> str:
        # Calls LLM with the prompt, returns the biological sentence
        ...

    sentences = build_sample_sentences(deep_study, summarize_fn=my_summarizer)
    for s in sentences:
        print(s.sentence)  # e.g. "Homo sapiens blood plasma, quality control
                           # pooled, from a targeted lipidomics study of 433
                           # lipids across 21 healthy human subjects."

Fallback (no LLM): bare-minimum facts-only string.
"""

from __future__ import annotations

import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from typing import Any, Callable

from mtbls_agent.models import StudyCandidate


# ── Public model ───────────────────────────────────────────────────


@dataclass
class SampleSentence:
    """A concise biological description of one sample."""

    study_id: str
    sample_name: str
    sentence: str
    """Pure biological description — no names, IDs, software, or techniques."""

    fields: dict[str, str]
    """Raw structured fields for downstream use."""


# ── Prompt template (for the agent's LLM) ─────────────────────────


BIO_SENTENCE_PROMPT = """\
From the biological sample data and study abstract below, write ONE concise \
sentence describing only the biological context of this sample.

SAMPLE DATA:
- Organism: {organism}
- Tissue: {tissue}
- Variant/Strain: {variant}
- Sample type: {sample_type}
- Biological factors: {factors}
- Disease/Condition: {condition}

STUDY ABSTRACT:
{abstract}

RULES:
- Include: organism, tissue, disease/condition, relevant biological factors
- Exclude: sample names, study accession numbers, software names, instrument \
models, analytical techniques, file formats
- Write exactly ONE sentence, concise but informative
- Use standard biomedical terminology"""


def build_bio_prompt(
    organism: str,
    tissue: str,
    variant: str,
    sample_type: str,
    factors: str,
    condition: str,
    abstract: str,
) -> str:
    """Build the LLM prompt for generating a biological sample description.

    The agent should pass this prompt to its LLM via the ``summarize_fn``
    callback.  The LLM response becomes the sample's ``sentence``.
    """
    return BIO_SENTENCE_PROMPT.format(
        organism=organism or "not specified",
        tissue=tissue or "not specified",
        variant=variant or "not specified",
        sample_type=sample_type or "not specified",
        factors=factors or "none",
        condition=condition or "none",
        abstract=abstract or "not specified",
    )


# ── Public API ─────────────────────────────────────────────────────


def build_sample_sentences(
    candidate: StudyCandidate,
    summarize_fn: Callable[[str], str] | None = None,
) -> list[SampleSentence]:
    """Generate biological descriptions for every sample in a study.

    When ``summarize_fn`` is provided (recommended), each sample's prompt
    (from :func:`build_bio_prompt`) is passed to it.  The LLM response
    becomes the sentence.

    When ``summarize_fn`` is ``None``, a minimal facts-only fallback is used.
    """
    if not candidate.sample_file_parsed or not candidate.sample_metadata:
        return []

    # ── Study-level context ─────────────────────────────────────────
    organism_default = _first_term(candidate.organisms)
    tissue_default = _first_term(candidate.organism_parts)
    condition = ", ".join(d.term for d in candidate.design_descriptors)
    raw_abstract = _clean_html(candidate.description or "")

    # ── Column discovery ────────────────────────────────────────────
    f = candidate.sample_metadata_fields or []
    char_cols = _find_characteristic_columns(f)
    factor_cols = _find_factor_columns(f)

    sentences: list[SampleSentence] = []

    for row in candidate.sample_metadata:
        sample_name = row.get("Source Name") or row.get("Sample Name") or "unknown"

        # Tabular biological data
        organism = _get_char(row, char_cols, "Organism") or organism_default
        tissue = _get_char(row, char_cols, "Organism part") or tissue_default
        variant = _get_char(row, char_cols, "Variant")
        sample_type = _get_char(row, char_cols, "Sample type")

        # Factor values
        factor_parts: list[str] = []
        factor_map: dict[str, str] = {}
        for col_name, full_col in factor_cols:
            val = row.get(full_col, "").strip()
            if val:
                label = col_name.replace("Factor Value[", "").rstrip("]").strip()
                factor_parts.append(f"{label}: {val}")
                factor_map[label] = val

        factors_str = "; ".join(factor_parts)

        if summarize_fn is not None:
            # LLM-generated description via prompt
            prompt = build_bio_prompt(
                organism=organism,
                tissue=tissue,
                variant=variant,
                sample_type=sample_type,
                factors=factors_str,
                condition=condition,
                abstract=raw_abstract,
            )
            sentence = summarize_fn(prompt)
        else:
            # Fallback: minimal facts-only string
            parts = [organism]
            if tissue and tissue.lower() != organism.lower():
                parts.append(tissue)
            if variant:
                parts.append(variant)
            if sample_type:
                parts.append(sample_type)
            if factor_parts:
                parts.append("(" + "; ".join(factor_parts) + ")")
            if condition:
                parts.append("[" + condition + "]")
            sentence = ", ".join(parts) + "."

        # Structured fields
        all_fields = {
            "sample": sample_name,
            "study": candidate.study_id,
            "organism": organism,
            "tissue": tissue,
            "variant": variant or "",
            "sample_type": sample_type or "",
            "condition": condition or "",
            "abstract": raw_abstract[:200] if raw_abstract else "",
            **factor_map,
        }

        sentences.append(
            SampleSentence(
                study_id=candidate.study_id,
                sample_name=sample_name,
                sentence=sentence,
                fields=all_fields,
            )
        )

    return sentences


def build_sample_sentences_batch(
    candidates: list[StudyCandidate],
    summarize_fn: Callable[[str], str] | None = None,
    max_workers: int = 10,
) -> list[list[SampleSentence]]:
    """Generate sentences for multiple studies in parallel."""
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futs = {
            ex.submit(build_sample_sentences, c, summarize_fn): i
            for i, c in enumerate(candidates)
        }
        results: list[list[SampleSentence] | None] = [None] * len(candidates)
        for fut in as_completed(futs):
            idx = futs[fut]
            results[idx] = fut.result()
    return [r for r in results if r is not None]


# ── Helpers ────────────────────────────────────────────────────────


def _clean_html(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _first_term(terms: list[Any]) -> str:
    for t in terms:
        if hasattr(t, "term") and t.term:
            return t.term
        if isinstance(t, dict) and t.get("term"):
            return t["term"]
    return ""


def _find_characteristic_columns(fields: list[str]) -> dict[str, str]:
    cols: dict[str, str] = {}
    for f in fields:
        if "Characteristics[" in f:
            key = f[f.index("[") + 1 : f.index("]")]
            if key not in cols:
                cols[key] = f
    return cols


def _find_factor_columns(fields: list[str]) -> list[tuple[str, str]]:
    return [(f, f) for f in fields if "Factor Value[" in f]


def _get_char(row: dict[str, str], char_cols: dict[str, str], key: str) -> str:
    col = char_cols.get(key)
    if col and col in row:
        return (row.get(col) or "").strip()
    return ""