"""SampleManifest — traceability between ISA metadata, samples, sentences, and files.

Provides both hierarchical (study → samples) and flat (CSV) views for
downstream ML workflows.
"""

from __future__ import annotations

import csv
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from metabo_search.downloader import DataFileRef
from metabo_search.models import StudyCandidate
from metabo_search.sample_gen import SampleDescription


@dataclass
class SampleEntry:
    """Everything known about one sample, fully resolved."""

    sample_name: str
    study_id: str

    # ── From the ISA-Tab sample file (s_*.txt) ──
    organism: str = ""
    tissue: str = ""
    variant: str = ""
    sample_type: str = ""
    factors: dict[str, str] = field(default_factory=dict)
    raw_sample_row: dict[str, str] = field(default_factory=dict)

    # ── From the assay file (a_*.txt) ──
    assay_techniques: list[str] = field(default_factory=list)
    assay_instruments: list[str] = field(default_factory=list)

    # ── Generated by the skill ──
    sentence: str = ""
    """BioBERT-ready biological description."""
    sentence_fields: dict[str, str] = field(default_factory=dict)

    # ── Linked data files ──
    raw_data_files: list[str] = field(default_factory=list)
    derived_data_files: list[str] = field(default_factory=list)

    @property
    def has_raw_data(self) -> bool:
        return len(self.raw_data_files) > 0

    def to_row(self) -> dict[str, Any]:
        return {
            "sample": self.sample_name,
            "study": self.study_id,
            "organism": self.organism,
            "tissue": self.tissue,
            "variant": self.variant,
            "sample_type": self.sample_type,
            **{f"factor_{k}": v for k, v in self.factors.items()},
            "assay_techniques": "; ".join(self.assay_techniques),
            "assay_instruments": "; ".join(self.assay_instruments),
            "sentence": self.sentence,
            "raw_data_files": "; ".join(self.raw_data_files[:5]),
            "derived_data_files": "; ".join(self.derived_data_files[:5]),
            "has_raw_data": self.has_raw_data,
        }


@dataclass
class StudyEntry:
    study_id: str
    title: str
    sample_count: int
    samples: list[SampleEntry] = field(default_factory=list)
    isa_sources: list[str] = field(default_factory=list)


@dataclass
class SampleManifest:
    studies: dict[str, StudyEntry] = field(default_factory=dict)
    samples: dict[str, list[SampleEntry]] = field(default_factory=dict)
    table_columns: list[str] = field(default_factory=list)
    table_rows: list[list[Any]] = field(default_factory=list)

    @classmethod
    def build(
        cls,
        candidates: list[StudyCandidate],
        sentences_map: dict[str, list[SampleDescription]] | None = None,
        data_files_map: dict[str, list[DataFileRef]] | None = None,
    ) -> SampleManifest:
        """Build a manifest from inspected studies + optional generated content.

        Sample resolution prefers **Sample Name** (the key used by the sentence
        generator and the assay-derived file map), falling back to Source Name —
        they differ in some studies (e.g. HuMet: WCQA-* vs numeric IDs).
        """
        manifest = cls()

        for c in candidates:
            sid = c.study_id
            study_sentences = (sentences_map or {}).get(sid, [])
            study_data_files = (data_files_map or {}).get(sid, [])
            sentence_by_name = {s.sample_name: s for s in study_sentences}

            entries = []
            for row in c.sample_metadata or []:
                src_name = row.get("Source Name") or ""
                samp_name = row.get("Sample Name") or ""
                sample_name = samp_name or src_name or "unknown"
                sent = sentence_by_name.get(sample_name)

                # Primary: assay-derived sample→file mapping (exact).  Try
                # Sample Name, then Source Name; else token-match fallback.
                file_map = c.sample_file_map or {}
                mapped = file_map.get(sample_name) or file_map.get(src_name, {})
                if mapped:
                    sample_raw = list(mapped.get("raw", []))
                    sample_derived = list(mapped.get("derived", []))
                else:
                    sample_raw = [
                        f.relative_path for f in study_data_files
                        if f.category == "raw" and _sample_matches(sample_name, f.relative_path)
                    ]
                    sample_derived = [
                        f.relative_path for f in study_data_files
                        if f.category == "derived" and _sample_matches(sample_name, f.relative_path)
                    ]

                entry = SampleEntry(
                    sample_name=sample_name,
                    study_id=sid,
                    organism=_get_field(row, c.organisms, "Organism"),
                    tissue=_get_field(row, c.organism_parts, "Organism part"),
                    variant=_get_char(row, c.sample_metadata_fields, "Variant"),
                    sample_type=_get_char(row, c.sample_metadata_fields, "Sample type"),
                    factors=_extract_factors(row, c.sample_metadata_fields),
                    raw_sample_row=row,
                    assay_techniques=sorted({
                        a.technique_name for a in c.assays if a.technique_name}),
                    assay_instruments=sorted({
                        a.instrument for a in c.assays if a.instrument}),
                    sentence=sent.sentence if sent else "",
                    sentence_fields=_used_sources_to_dict(sent.used_sources) if sent else {},
                    raw_data_files=sample_raw,
                    derived_data_files=sample_derived,
                )
                entries.append(entry)

            isa_sources = ["i_Investigation.txt"]
            for fname in (c.sample_metadata_fields or []):
                if fname.startswith(("s_", "a_", "m_")):
                    isa_sources.append(fname)

            manifest.studies[sid] = StudyEntry(
                study_id=sid,
                title=c.title or "",
                sample_count=len(entries),
                samples=entries,
                isa_sources=sorted(set(isa_sources)),
            )
            manifest.samples[sid] = entries

        if manifest.samples:
            all_rows = [e.to_row() for entries in manifest.samples.values()
                        for e in entries]
            if all_rows:
                manifest.table_columns = list(all_rows[0].keys())
                manifest.table_rows = [
                    [row.get(col, "") for col in manifest.table_columns]
                    for row in all_rows
                ]
        return manifest

    def export_csv(self, path: str | Path) -> None:
        if not self.table_rows:
            raise ValueError("No data to export")
        with open(path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(self.table_columns)
            writer.writerows(self.table_rows)

    def filter_samples(self, **conditions: Any) -> list[SampleEntry]:
        results = []
        for entries in self.samples.values():
            for e in entries:
                if all(getattr(e, key, None) == val for key, val in conditions.items()):
                    results.append(e)
        return results

    @property
    def all_sentences(self) -> list[str]:
        return [e.sentence for entries in self.samples.values()
                for e in entries if e.sentence]

    @property
    def total_samples(self) -> int:
        return sum(len(entries) for entries in self.samples.values())


# ── Helpers ────────────────────────────────────────────────────────


def _used_sources_to_dict(used: list[str]) -> dict[str, str]:
    out = {}
    for item in used:
        if "=" in item:
            k, v = item.split("=", 1)
            out[k] = v
    return out


def _sample_matches(sample_name: str, relative_path: str) -> bool:
    """Match sample name to data filename via multiset token matching.

    Data files encode extra tokens beyond the sample name (e.g. ``_neg_``,
    ``_b2``).  We require every token of the sample name to appear in the
    file's tokens *with multiplicity* — a plain set would let
    ``1_LTR_1_A-1`` match ``1_LTR_1_A-2``.
    """
    if not sample_name:
        return False

    fname = relative_path.split("/")[-1]
    # Strip ALL suffixes (handles compound ext like 1_LTR_1_A-1.d.zip),
    # not just the last one which would leave "1.d" glued.
    base = fname
    for _ in range(len(Path(fname).suffixes)):
        base = Path(base).stem
    base = base.lower()
    s_lower = sample_name.lower()

    if s_lower == base:  # exact
        return True

    sample_tokens = Counter(re.split(r"[_\-\s]+", s_lower))
    file_counter = Counter(re.split(r"[_\-\s]+", base))
    if not sample_tokens <= file_counter:
        return False

    # Numeric tokens must match exactly (not substring/prefix):
    # prevents "QC_1" from matching "QC_12".
    sample_nums = {t for t in sample_tokens if t.isdigit()}
    file_nums = {t for t in file_counter if t.isdigit()}
    if sample_nums and not sample_nums.issubset(file_nums):
        return False
    return True


def _get_field(row: dict[str, str], ontology_terms: list[Any], key: str) -> str:
    val = _get_char(row, list(row.keys()), key)
    if val:
        return val
    for t in ontology_terms:
        if hasattr(t, "term") and t.term:
            return t.term
    return ""


def _get_char(row: dict[str, str], fields: list[str], key: str) -> str:
    for f in fields:
        if key in f and "Characteristics[" in f:
            val = row.get(f, "").strip()
            if val:
                return val
    return ""


def _extract_factors(row: dict[str, str], fields: list[str] | None) -> dict[str, str]:
    factors: dict[str, str] = {}
    for f in fields or []:
        if "Factor Value[" in f:
            label = f.replace("Factor Value[", "").rstrip("]").strip()
            val = row.get(f, "").strip()
            if val:
                factors[label] = val
    return factors